version: '3.9'
services:
  kissudb:
    image: mysql:5.7
    volumes:
       - mysql_storage:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kissu7379
      MYSQL_USER: Kishore
      MYSQL_PASSWORD: redhatkissu
      MYSQL_DATABASE: kissudb


  wordpress:
    image: WordPress:latest
    restart: always
    depends_on:
      - kissudb
    ports:
      - 8809:80
    volumes:
      - wp_storage:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: kissudb:3306
      WORDPRESS_DB_USER: Kishore
      WORDPRESS_DB_PASSWORD: redhatkissu
      WORDPRESS_DB_NAME: wordpress

volumes:
  mysql_storage: {}
  wp_storage: {}
